### ISSUE TITLE
SPOTIFY - playlist & artist not working

### ISSUE THREAD

**Issue by Tomato6966** [TopiSenpai/LavaSrc#13]
Artist link: https://open.spotify.com/artist/3ZztVuWxHzNpl0THurTFCv

Playlist Link: https://open.spotify.com/playlist/37i9dQZF1DXc6IFF23C9jj

- not just I have that error...

My java version: Openjdk 18

My lavalink version 3.5.1 and also tested with dev same errors.

My lavasrc version : 3.0.1

<details>
<summary>My lavasrc settings:</summary>

```yml
plugins:

  lavasrc:
    providers:
      - "dzisrc:\"%ISRC%\""
      - "dzsearch:%QUERY%"
      - "scsearch:%QUERY%"
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: true
      deezer: true
    spotify:
      clientId: "..."
      clientSecret: "...."
      countryCode: "US"
    applemusic:
      countryCode: "US" 
    deezer:
      masterDecryptionKey: "g....1"
```
</details>

<details>

<summary>Error for playlist</summary>

```
2022-10-08 09:47:24.613  INFO 1727487 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/playlist/37i9dQZF1DXc6IFF23C9jj"
2022-10-08 09:47:25.541  INFO 1727487 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist null
2022-10-08 09:47:25.553 ERROR 1727487 --- [  XNIO-1 task-1] io.undertow.request                      : UT005023: Exception handling request to /loadtracks

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar!/:5.3.18]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:182) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$2$1.handleRequest(AsyncContextImpl.java:201) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$2.run(AsyncContextImpl.java:195) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$6.run(AsyncContextImpl.java:472) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:591) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:359) ~[na:na]
        at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.encodeTrack(DefaultAudioPlayerManager.java:248) ~[lavaplayer-1.3.98.4.jar!/:na]
        at lavalink.server.util.Util.toMessage(Util.java:49) ~[classes!/:na]
        at lavalink.server.player.AudioLoaderRestHandler.lambda$encodeLoadResult$0(AudioLoaderRestHandler.java:89) ~[classes!/:na]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[na:na]
        at lavalink.server.player.AudioLoaderRestHandler.encodeLoadResult(AudioLoaderRestHandler.java:84) ~[classes!/:na]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
        at lavalink.server.player.AudioLoader.playlistLoaded(AudioLoader.java:89) ~[classes!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:446) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        ... 1 common frames omitted
```

</details>

<details>
<summary>Error for artists</summary>

```
2022-10-08 07:56:00.724  INFO 1717673 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/artist/3ZztVuWxHzNpl0THurTFCv"
2022-10-08 07:56:00.769  WARN 1717673 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Suspicious exception for loading item https://open.spotify.com/artist/3ZztVuWxHzNpl0THurTFCv

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getJson(SpotifySourceManager.java:138) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getArtist(SpotifySourceManager.java:210) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:110) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.19.5-051905-generic
  java.vendor: Oracle Corporation
  java.version: 18.0.2.1
  java.runtime.version: 18.0.2.1+1-1
  java.vm.version: 18.0.2.1+1-1
Caused by: java.lang.IllegalStateException: Response code from channel info is 400
        ... 11 common frames omitted

2022-10-08 07:56:00.769 ERROR 1717673 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getJson(SpotifySourceManager.java:138) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getArtist(SpotifySourceManager.java:210) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:110) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.19.5-051905-generic
  java.vendor: Oracle Corporation
  java.version: 18.0.2.1
  java.runtime.version: 18.0.2.1+1-1
  java.vm.version: 18.0.2.1+1-1
Caused by: java.lang.IllegalStateException: Response code from channel info is 400
        ... 11 common frames omitted

2022-10-08 07:56:00.770 ERROR 1717673 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getJson(SpotifySourceManager.java:138) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.getArtist(SpotifySourceManager.java:210) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:110) ~[lavasrc-plugin-3.0.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:436) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.19.5-051905-generic
  java.vendor: Oracle Corporation
  java.version: 18.0.2.1
  java.runtime.version: 18.0.2.1+1-1
  java.vm.version: 18.0.2.1+1-1
Caused by: java.lang.IllegalStateException: Response code from channel info is 400
        ... 11 common frames omitted
```</details>

**Comment by TopiSenpai** [comment]
fixed in https://github.com/TopiSenpai/LavaSrc/releases/tag/3.0.2
