### ISSUE TITLE
Error with Deezer search

### ISSUE THREAD

**Issue by IdkWhosThis** [TopiSenpai/LavaSrc#21]
**Lavalink**: `3.6.0`
**LavaSrc**: `3.1.0`
**JVM**: `13.0.2`

I have ran into an issue with the Deezer search. When I try to search anything using `dzsearch:` I end up with an error in the console.

Error log: (Provided by: @TopiSenpai)
```
2022-10-22 17:43:02.494  INFO 1 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "dzsearch:powerolf - my will be done"
2022-10-22 17:43:03.238  INFO 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Deezer Search: powerolf - my will be done
2022-10-22 17:43:08.421  INFO 1 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"play","guildId":"592763557515362324","track":"QAAA1QIAD015IFdpbGwgQmUgRG9uZQAJUG93ZXJ3b2xmAAAAAAADYzAACjE5NDYzMjk2ODcAAQAjaHR0cHM6Ly9kZWV6ZXIuY29tL3RyYWNrLzE5NDYzMjk2ODcABmRlZXplcgABAGlodHRwczovL2UtY2Rucy1pbWFnZXMuZHpjZG4ubmV0L2ltYWdlcy9jb3Zlci9jODBlMDRlZGFlNjk2Yzc0NDI4OGMzNDk5ZGJhOTZmMi8xMDAweDEwMDAtMDAwMDAwLTgwLTAtMC5qcGcAAAAAAAAAAA=="}
2022-10-22 17:43:08.582 ERROR 1 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 1946329687

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.98.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[lavaplayer-1.3.98.4.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.3.98.4-original
  os.arch: amd64
  os.name: Linux
  os.version: 4.19.0-18-amd64
  java.vendor: Eclipse Adoptium
  java.version: 18.0.2.1
  java.runtime.version: 18.0.2.1+1
  java.vm.version: 18.0.2.1+1
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.sedmelluq.discord.lavaplayer.tools.JsonBrowser.as(java.lang.Class)" is null
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioTrack.getTrackMediaURI(DeezerAudioTrack.java:45) ~[lavasrc-plugin-3.1.0.jar!/:na]
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioTrack.process(DeezerAudioTrack.java:90) ~[lavasrc-plugin-3.1.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.98.4.jar!/:na]
        ... 4 common frames omitted
```

My Lavalink config:
```yml
lavalink:
  plugins:
  - dependency: com.github.TopiSenpai.LavaSrc:lavasrc-plugin:3.1.0
    repository: https://jitpack.io
  server:
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    gc-warnings: true
    opusEncodingQuality: 10
    password: youshallnotpass
    playerUpdateInterval: 5
    resamplingQuality: HIGH
    soundcloudSearchEnabled: true
    sources:
      bandcamp: true
      http: true
      local: false
      mixer: true
      soundcloud: true
      twitch: true
      vimeo: true
      youtube: false
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    youtubeSearchEnabled: false
logging:
  file:
    max-history: 30
    max-size: 1GB
  level:
    lavalink: INFO
    root: INFO
  path: ./logs/
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
plugins:
  lavasrc:
    deezer:
      masterDecryptionKey: key
    providers:
    - dzsearch:%QUERY%
    - dzisrc:%ISRC%
    - scsearch:%QUERY%
    sources:
      applemusic: false
      deezer: true
      spotify: true
      yandexmusic: false
    spotify:
      clientId: id
      clientSecret: secret
      countryCode: US
sentry:
  dsn: ""
  environment: ""
server:
  address: 0.0.0.0
  port: 2333
```

**Comment by TopiSenpai** [comment]
should be fixed in https://github.com/TopiSenpai/LavaSrc/releases/tag/3.1.1
