### ISSUE TITLE
Error with Apple Music

### ISSUE THREAD

**Issue by AlejandroMesa22** [TopiSenpai/LavaSrc#25]
Well, while I was testing Apple Music URLs, this returned an error and didn't play anything. Here I will attach some screenshots of what appeared in the terminal.
![20221028_184537](https://user-images.githubusercontent.com/64811192/198751276-d8ed09cb-eff8-4ad0-818e-90240f4e2449.png)
![20221028_184610](https://user-images.githubusercontent.com/64811192/198751282-4276e2eb-8f44-4202-b6ff-0a08dc9b4db2.png)
![20221028_184653](https://user-images.githubusercontent.com/64811192/198751285-6b5d21ff-4688-4c26-8ea2-75d6ef4a094c.png)

**Comment by TopiSenpai** [comment]
It seems like apple music change the token location on their website

**Comment by AlejandroMesa22** [comment]
Hmm, so this can be fixed?

**Comment by TopiSenpai** [comment]
We will see if we can grab the token from somewhere else

**Comment by TopiSenpai** [comment]
the token seems to be embedded into one of the js files now
we need to figure out a reliable way to extract that then we are good to go again

**Comment by TopiSenpai** [comment]
alright I got a kind of dirty fix for this
see https://github.com/TopiSenpai/LavaSrc/pull/28

feel free to test it & report back

**Comment by AlejandroMesa22** [comment]
After trying it I got this error in the terminal (And again it did not play anything)

```
2022-11-02 12:01:10.947  INFO 11504 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://music.apple.com/co/album/not-out-of-my-mind-single/1639209772"
2022-11-02 12:01:16.854  WARN 11504 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Suspicious exception for loading item https://music.apple.com/co/album/not-out-of-my-mind-single/1639209772

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.99.jar!/:na]
        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.getJson(AppleMusicSourceManager.java:163) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.getAlbum(AppleMusicSourceManager.java:175) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]
        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.loadItem(AppleMusicSourceManager.java:99) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:424) ~[lavaplayer-1.3.99.jar!/:na]        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.3.99.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.99-original
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 19.0.1
  java.runtime.version: 19.0.1+10-21
  java.vm.version: 19.0.1+10-21
Caused by: java.lang.IllegalStateException: Response code from channel info is 401
        ... 11 common frames omitted

2022-11-02 12:01:16.888 ERROR 11504 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.99.jar!/:na]
        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.getJson(AppleMusicSourceManager.java:163) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.getAlbum(AppleMusicSourceManager.java:175) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]
        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.loadItem(AppleMusicSourceManager.java:99) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:424) ~[lavaplayer-1.3.99.jar!/:na]        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.3.99.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.99-original
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 19.0.1
  java.runtime.version: 19.0.1+10-21
  java.vm.version: 19.0.1+10-21
Caused by: java.lang.IllegalStateException: Response code from channel info is 401
        ... 11 common frames omitted

2022-11-02 12:01:16.984 ERROR 11504 --- [ader-2-thread-1] l.server.player.AudioLoaderRestHandler   : Track loading failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Server responded with an error.
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.fetchResponseAsJson(HttpClientTools.java:261) ~[lavaplayer-1.3.99.jar!/:na]
        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.getJson(AppleMusicSourceManager.java:163) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.getAlbum(AppleMusicSourceManager.java:175) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]
        at com.github.topisenpai.lavasrc.applemusic.AppleMusicSourceManager.loadItem(AppleMusicSourceManager.java:99) ~[jar:file:C:\Users\Alejandro\Desktop\Discord Music Bot\.\plugins\lavasrc-plugin-bd1296a.jar!/:na]        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:424) ~[lavaplayer-1.3.99.jar!/:na]        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.3.99.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.99-original
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 19.0.1
  java.runtime.version: 19.0.1+10-21
  java.vm.version: 19.0.1+10-21
Caused by: java.lang.IllegalStateException: Response code from channel info is 401
        ... 11 common frames omitted

2022-11-02 12:01:17.100  INFO 11504 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"657456417078509578","volume":100}
2022-11-02 12:01:18.574  INFO 11504 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /[0:0:0:0:0:0:0:1]:54307 -- CloseStatus[code=1006, reason=]
2022-11-02 12:01:18.608  INFO 11504 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
```

**Comment by JU5TDIE** [comment]
401 error, I guess it's header problem. I got 200 response code when I added "Origin" in header.

**Comment by TopiSenpai** [comment]
oh yeah I forgot to prefix the origin extracted from the jwt with `https://`
try again

**Comment by AlejandroMesa22** [comment]
I have tried several songs and everything works fine so far. Thanks for fixing it

**Comment by TopiSenpai** [comment]
fixed in https://github.com/TopiSenpai/LavaSrc/releases/tag/3.1.4

**Comment by JU5TDIE** [comment]
It's broken again. Token variable part in js file has been changed to `const Sd = `

**Comment by TopiSenpai** [comment]
I already have an alternative regex
for now change

**Comment by TopiSenpai** [comment]
feel free to try `cee366e`

**Comment by JU5TDIE** [comment]
> feel free to try `cee366e`

Works well

**Comment by TopiSenpai** [comment]
again fixed in https://github.com/TopiSenpai/LavaSrc/releases/tag/3.1.5
