### ISSUE TITLE
YandexMusic UT005023: Exception handling request to /loadtracks

### ISSUE THREAD

**Issue by Omniplast** [TopiSenpai/LavaSrc#26]
When i try get any request on yandexmusic, i receive this. 

Lavalink: 3.6.1
Java: 13.0.7
LavaSrc: 3.1.2

```
2022-10-29 13:39:20.802  INFO 164570 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://music.yandex.ru/album/13886032"
2022-10-29 13:39:20.973  INFO 164570 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "727269080331059201", "sessionId": "1ce46dbc6821c0ec956b8408b8c4b1ac", "event": {"token": "6a2e5e398cbb0a8a", "guild_id": "727269080331059201", "endpoint": "russia1570.discord.media:443"}}
2022-10-29 13:39:21.286  INFO 164570 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist For Those That Wish To Exist
2022-10-29 13:39:21.383 ERROR 164570 --- [  XNIO-1 task-2] io.undertow.request                      : UT005023: Exception handling request to /loadtracks

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.18.jar!/:5.3.18]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.18.jar!/:5.3.18]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.18.jar!/:5.3.18]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:182) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$2$1.handleRequest(AsyncContextImpl.java:201) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$2.run(AsyncContextImpl.java:195) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$6.run(AsyncContextImpl.java:472) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.spec.AsyncContextImpl$TaskDispatchRunnable.run(AsyncContextImpl.java:591) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) ~[jboss-threads-3.1.0.Final.jar!/:3.1.0.Final]
        at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Caused by: java.lang.NullPointerException: null
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.encodeTrackDetails(DefaultAudioPlayerManager.java:310) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.encodeTrack(DefaultAudioPlayerManager.java:261) ~[lavaplayer-1.3.99.jar!/:na]
        at lavalink.server.util.Util.toMessage(Util.java:49) ~[classes!/:na]
        at lavalink.server.player.AudioLoaderRestHandler.lambda$encodeLoadResult$0(AudioLoaderRestHandler.java:89) ~[classes!/:na]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1508) ~[na:na]
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[na:na]
        at lavalink.server.player.AudioLoaderRestHandler.encodeLoadResult(AudioLoaderRestHandler.java:84) ~[classes!/:na]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2144) ~[na:na]
        at lavalink.server.player.AudioLoader.playlistLoaded(AudioLoader.java:89) ~[classes!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:452) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:424) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.3.99.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        ... 1 common frames omitted
```

**Comment by TopiSenpai** [comment]
@AgutinVBoy can you look into this?

**Comment by AgutinVBoy** [comment]
@Omniplast Hey. Does this happen with any request or just this album?

**Comment by AgutinVBoy** [comment]
I think I got the reason. Yandex Music is very location-dependent. You should either have a premium subscription or be located in one of the CIS countries (страны СНГ).

**Comment by Omniplast** [comment]
> @OmniplastПривет. Это происходит с любым запросом или только с этим альбомом? UPD: У меня работает, вот и пытаюсь понять, почему у вас не работает.
Да, такая проблема вообще с любым запросом. Пробовал запускать lavalink у себя, ошибка та же.

**Comment by AgutinVBoy** [comment]
Либо аккаунт должен иметь яндекс.плюс, либо запросы должны идти из стран СНГ. Попробуй для теста подкасты - должны работать при любых обстоятельствах

**Comment by Omniplast** [comment]
> Либо аккаунт должен иметь яндекс.плюс, либо запросы должны идти из стран СНГ. Попробуй для теста подкасты - должны работать при любых обстоятельствах

Да, я сразу с подкастами и стал пробовать - эффекта нету.

**Comment by AgutinVBoy** [comment]
Можешь связаться со мной в дискорде? Есть пара вопросов. Eterna#9999

**Comment by AgutinVBoy** [comment]
@TopiSenpai unfortunately, I can not identify the cause of this bug. All api requirements are met. To be honest, I don't understand how it is possible to cause such an error. The lavasrc code seems to be fine. 

It uses python + lavalink.

**Comment by TopiSenpai** [comment]
The album's work fine for you?

**Comment by AgutinVBoy** [comment]
> The album's work fine for you?

yes

**Comment by TopiSenpai** [comment]
urgh annoying
how the hell is even the source manager null

**Comment by TopiSenpai** [comment]
@Omniplast can you try with version `c9578f4`?

**Comment by Omniplast** [comment]
> @Omniplast can you try with version `c9578f4`?

Wow, its work

**Comment by TopiSenpai** [comment]
fixed in https://github.com/TopiSenpai/LavaSrc/releases/tag/3.1.3
