### ISSUE TITLE
Spotify java.io.EOFException: null

### ISSUE THREAD

**Issue by Andreychik32** [TopiSenpai/LavaSrc#43]
Hi! When I give this input URL to lavalink (https://open.spotify.com/track/5EWPGh7jbTNO2wakv8LjUI?si=2c42125d4c7a497d), I get this error:

```
java.io.EOFException: null
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203) ~[na:na]
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[na:na]
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.tools.DataFormatTools.readNullableText(DataFormatTools.java:184) ~[lavaplayer-1.3.99.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.decodeTrack(SpotifySourceManager.java:81) ~[jar:file:!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.decodeTrackDetails(DefaultAudioPlayerManager.java:334) ~[lavaplayer-1.3.99.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.decodeTrack(DefaultAudioPlayerManager.java:278) ~[lavaplayer-1.3.99.1.jar!/:na]
        at lavalink.server.util.Util.toAudioTrack(Util.java:44) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.play(WebSocketHandler.kt:81) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.access$play(WebSocketHandler.kt:16) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler$handlers$2.invoke(WebSocketHandler.kt:30) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler$handlers$2.invoke(WebSocketHandler.kt:16) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.handle(WebSocketHandler.kt:49) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessageSafe(SocketServer.kt:171) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessage(SocketServer.kt:151) ~[classes!/:na]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:288) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:600) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.invokeTextHandler(FrameHandler.java:268) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.onFullTextMessage(FrameHandler.java:319) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.onText(FrameHandler.java:184) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:955) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:935) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) ~[xnio-nio-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) ~[xnio-nio-3.8.6.Final.jar!/:3.8.6.Final]
```

Plugin version is `3.1.9`, lavalink is `3.6.2`.

**Comment by Andreychik32** [comment]
Something's wrong [here](https://github.com/TopiSenpai/LavaSrc/blob/ad2298259fde47bcfe0825499e74a6dac1152781/main/src/main/java/com/github/topisenpai/lavasrc/spotify/SpotifySourceManager.java#L81), i suppose. But I can't debug it :(

**Comment by TopiSenpai** [comment]
which lavalink client do you use?

**Comment by Andreychik32** [comment]
> which lavalink client do you use?

I use my own implementation with sponsorblock features based on disgolink.

I haven't supplied you with complete log message. Here it is:
```java
2023-01-01 21:36:25.221  INFO 21916 --- [           main] lavalink.server.Launcher                 : Starting Launcher using Java 19 on DESKTOP-V24PS77 with PID 21916
2023-01-01 21:36:25.224  INFO 21916 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-01-01 21:36:25.821  INFO 21916 --- [           main] lavalink.server.bootstrap.PluginManager  : Deleted .\plugins\lavasrc-plugin-3.1.9.jar
2023-01-01 21:36:25.827  INFO 21916 --- [           main] lavalink.server.bootstrap.PluginManager  : Downloading https://jitpack.io/com/github/TopiSenpai/LavaSrc/lavasrc-plugin/3.1.9/lavasrc-plugin-3.1.9.jar
2023-01-01 21:36:27.064  INFO 21916 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'lavasrc' version 3.1.9
2023-01-01 21:36:27.081  INFO 21916 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded lavasrc-plugin-3.1.7.jar (22 classes)
2023-01-01 21:36:27.081  INFO 21916 --- [           main] lavalink.server.bootstrap.PluginManager  : Found plugin 'SponsorBlock-Plugin' version 1.0.5
2023-01-01 21:36:27.085  INFO 21916 --- [           main] lavalink.server.bootstrap.PluginManager  : Loaded Sponsorblock-Plugin-1.0.5.jar (4 classes)
2023-01-01 21:36:27.210  INFO 21916 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.383 seconds (JVM running for 2.713)
2023-01-01 21:36:27.212  INFO 21916 --- [           main] lavalink.server.Launcher                 : You can safely ignore the big red warning about illegal reflection. See https://github.com/freyacodes/Lavalink/issues/295
2023-01-01 21:36:27.251  INFO 21916 --- [           main] lavalink.server.Launcher                 :

←[32m       .  ←[31m _                  _ _       _    ←[32m__ _ _
←[32m      /\\ ←[31m| | __ ___   ____ _| (_)_ __ | | __←[32m\ \ \ \
←[32m     ( ( )←[31m| |/ _` \ \ / / _` | | | '_ \| |/ /←[32m \ \ \ \
←[32m      \\/ ←[31m| | (_| |\ V / (_| | | | | | |   < ←[32m  ) ) ) )
←[32m       '  ←[31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\←[32m / / / /
←[0m    =========================================←[32m/_/_/_/←[0m

        Version:        3.6.2
        Build time:     08.11.2022 09:02:53 UTC
        Branch          HEAD
        Commit:         4782f1f
        Commit time:    08.11.2022 09:01:14 UTC
        JVM:            19
        Lavaplayer      1.3.99.1-original

2023-01-01 21:36:27.258  INFO 21916 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2023-01-01 21:36:27.686  WARN 21916 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-01-01 21:36:27.707  INFO 21916 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-01-01 21:36:27.707  INFO 21916 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 445 ms
2023-01-01 21:36:27.751  INFO 21916 --- [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Loading LavaSrc plugin...
2023-01-01 21:36:27.752  INFO 21916 --- [           main] c.g.t.p.sponsorblock.SponsorBlockPlugin  : Loading SponsorBlock Plugin...
2023-01-01 21:36:27.822  INFO 21916 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2023-01-01 21:36:27.843  INFO 21916 --- [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Registering Spotify audio source manager...
2023-01-01 21:36:27.967  INFO 21916 --- [           main] lavalink.server.config.KoeConfiguration  : OS: WINDOWS, Arch: X86_64
2023-01-01 21:36:27.967  INFO 21916 --- [           main] lavalink.server.config.KoeConfiguration  : Enabling JDA-NAS
2023-01-01 21:36:27.969  INFO 21916 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2023-01-01 21:36:27.974  INFO 21916 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2023-01-01 21:36:27.989  WARN 21916 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
2023-01-01 21:36:28.176  INFO 21916 --- [           main] io.undertow                              : starting server: Undertow - 2.2.16.Final
2023-01-01 21:36:28.181  INFO 21916 --- [           main] org.xnio                                 : XNIO version 3.8.6.Final
2023-01-01 21:36:28.187  INFO 21916 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.6.Final
2023-01-01 21:36:28.248  INFO 21916 --- [           main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2023-01-01 21:36:28.288  INFO 21916 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 2333 (http)
2023-01-01 21:36:28.291  INFO 21916 --- [           main] lavalink.server.Launcher                 : Started Launcher in 1.075 seconds (JVM running for 3.794)
2023-01-01 21:36:28.292  INFO 21916 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
2023-01-01 21:36:48.234  INFO 21916 --- [  XNIO-1 task-1] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-01-01 21:36:48.234  INFO 21916 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-01-01 21:36:48.235  INFO 21916 --- [  XNIO-1 task-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
2023-01-01 21:36:48.246  INFO 21916 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /[0:0:0:0:0:0:0:1]:49900
2023-01-01 21:36:48.279  INFO 21916 --- [  XNIO-1 task-1] lavalink.server.io.SocketServer          : Connection successfully established from disgolink/v0.14.1
2023-01-01 21:36:54.610  INFO 21916 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/track/5EWPGh7jbTNO2wakv8LjUI?si=2c42125d4c7a497d"
2023-01-01 21:36:54.939  INFO 21916 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Free Bird
2023-01-01 21:36:54.955  INFO 21916 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : {"op":"play","guildId":"213661994270588929","track":"QAAAhgIACUZyZWUgQmlyZAAOTHlueXJkIFNreW55cmQAAAAAAAhZIgAWNUVXUEdoN2piVE5PMndha3Y4TGpVSQABADVodHRwczovL29wZW4uc3BvdGlmeS5jb20vdHJhY2svNUVXUEdoN2piVE5PMndha3Y4TGpVSQAHc3BvdGlmeQEADFVTTUMx","skipSegments":["music_offtopic","filler","interaction","intro","outro","preview","selfpromo","sponsor"]}
2023-01-01 21:36:54.959 ERROR 21916 --- [   XNIO-1 I/O-6] lavalink.server.io.SocketServer          : Exception while handling websocket message

java.io.EOFException: null
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203) ~[na:na]
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[na:na]
        at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.tools.DataFormatTools.readNullableText(DataFormatTools.java:184) ~[lavaplayer-1.3.99.1.jar!/:na]
        at com.github.topisenpai.lavasrc.spotify.SpotifySourceManager.decodeTrack(SpotifySourceManager.java:80) ~[jar:file:!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.decodeTrackDetails(DefaultAudioPlayerManager.java:334) ~[lavaplayer-1.3.99.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.decodeTrack(DefaultAudioPlayerManager.java:278) ~[lavaplayer-1.3.99.1.jar!/:na]
        at lavalink.server.util.Util.toAudioTrack(Util.java:44) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.play(WebSocketHandler.kt:81) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.access$play(WebSocketHandler.kt:16) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler$handlers$2.invoke(WebSocketHandler.kt:30) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler$handlers$2.invoke(WebSocketHandler.kt:16) ~[classes!/:na]
        at lavalink.server.io.WebSocketHandler.handle(WebSocketHandler.kt:49) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessageSafe(SocketServer.kt:171) ~[classes!/:na]
        at lavalink.server.io.SocketServer.handleTextMessage(SocketServer.kt:151) ~[classes!/:na]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82) ~[spring-websocket-5.3.17.jar!/:5.3.17]
        at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:288) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:610) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:600) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.invokeTextHandler(FrameHandler.java:268) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.onFullTextMessage(FrameHandler.java:319) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.jsr.FrameHandler.onText(FrameHandler.java:184) ~[undertow-websockets-jsr-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:955) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:935) ~[undertow-core-2.2.16.Final.jar!/:2.2.16.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) ~[xnio-nio-3.8.6.Final.jar!/:3.8.6.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) ~[xnio-nio-3.8.6.Final.jar!/:3.8.6.Final]
```

**Comment by TopiSenpai** [comment]
Ah
Die disgolink you also require https://github.com/disgoorg/source-plugins

**Comment by Andreychik32** [comment]
That was indeed the issue. Thank you for your assistance!
